output:
  directory: outputs
  per_scan_report_dir: reports
  per_scan_report_format: all
  html_template: templates/report.html
  pdf_report: true
  export_formats: [json, html, csv, markdown, xml]
scan_settings:
  retries: 3
  timeout: 600
  rate_limit: 10
  threads: 5
  memory_limit_percent: 90
  shodan_api_key: your_shodan_key
  censys_api_id: your_censys_id
  censys_api_secret: your_censys_secret
  virustotal_api_key: your_virustotal_key
  dnsdb_api_key: your_dnsdb_key
  passivetotal_api_key: your_passivetotal_key
  amass_params: enum -active
  subfinder_params: -all
  httpx_params: -silent
  nuclei_templates: /path/to/nuclei/templates
  ffuf_wordlist: /usr/share/wordlists/dirb/common.txt
  ffuf_params: -c -t 50
  nmap_params: --script vuln
tools:
  amass: /usr/bin/amass
  subfinder: /usr/bin/subfinder
  findomain: /usr/bin/findomain
  assetfinder: /usr/bin/assetfinder
  sublist3r: /path/to/Sublist3r/sublist3r.py
  httpx: /usr/bin/httpx
  katana: /usr/bin/katana
  hakrawler: /usr/bin/hakrawler
  photon: /path/to/photon/photon.py
  waybackurls: /usr/bin/waybackurls
  gau: /usr/bin/gau
  arjun: /path/to/Arjun/arjun.py
  nuclei: /usr/bin/nuclei
  xsstrike: /path/to/XSStrike/xsstrike.py
  dalfox: /usr/bin/dalfox
  nikto: /usr/bin/nikto
  testssl: /usr/bin/testssl.sh
  ffuf: /usr/bin/ffuf
  nmap: /usr/bin/nmap
input_files:
  subdomains: subdomains.txt
  domains: domains.txt
  js: jsfiles.txt
  paths: paths.txt
  params: params.txt
  logs: [access.log, error.log]
notifications:
  enable: false
  slack_webhook: null
  discord_webhook: null
  telegram_bot_token: null
  telegram_chat_id: null
kamehameha:
  enable: true
  theme: blue
  charge_time: 5
  animation_speed: 0.2
